### ISSUE TITLE
Create Following View

### ISSUE THREAD

**Issue by Larke12** [octotep/twiccian#56]
Do we want a grid view? http://doc.qt.io/qt-4.8/qml-gridview.html

**Comment by flamwenco** [comment]
From issue #10:

> Add a feature which allow users to browse live streams from the streamers they follow.

**Comment by flamwenco** [comment]
From issue #34:

> Allow users to see a list of their following channels (broadcaster + game).

**Comment by Larke12** [comment]
https://web.archive.org/web/20130726020925/http://harmattan-dev.nokia.com/docs/platform-api-reference/xml/daily-docs/libqt4/qdeclarativemodels.html
