### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by octotep** [octotep/twiccian#8]
Add a feature which notifies a viewer when a streamer they follow goes live or when their username is mentioned in chat.
- [ ] Stream notifications
- [ ] Chat notifications

**Comment by Larke12** [comment]
Possible notifier to include, [TwitchNotifier](https://github.com/GiedriusS/TwitchNotifier).

**Comment by Larke12** [comment]
Moved to [Twicciand](https://github.com/octotep/twicciand)
